#+CATEGORY: congreso, comunicación, evento
#+TAGS: podcast, audio, multimedia
#+DESCRIPTION: Propuesta de realización de podcasts para las actividades del laboratorio de datos durante 2017
#+TITLE: Ecos de Medialab
#+DATE: <2017-02-08 mié 10:30>
#+AUTHOR: Adolfo Antón Bravo
#+EMAIL: adolfo@medialab-prado.es
#+OPTIONS: todo:nil pri:nil tags:nil ^:nil 

#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:nil reveal_control:t
#+OPTIONS: reveal_mathjax:t reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+OPTIONS: toc:nil
#+REVEAL_MARGIN: 0.1
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+REVEAL_TRANS: linear
#+REVEAL_THEME: sky
#+REVEAL_HLEVEL: 2
#+REVEAL_HEAD_PREAMBLE: <meta name="description" content="Org-Reveal Introduction.">
#+REVEAL_POSTAMBLE: <p> Creado por adolflow. </p>
#+REVEAL_PLUGINS: (highlight markdown notes)
#+REVEAL_EXTRA_CSS: file:///home/flow/Documentos/software/reveal.js/css/reveal.css
#+REVEAL_ROOT: file:///home/flow/Documentos/software/reveal.js/

El podcasting o podcast es radio bajo demanda, es decir, distribución
de archivos multimedia (normalmente audio o vídeo, que pueden incluir
texto como subtítulos y notas) mediante un sistema de redifusión (RSS)
que permite opcionalmente suscribirse y usar un programa que lo
descarga para que el usuario lo escuche. (Wikipedia, https://es.wikipedia.org/wiki/Podcasting)

Su origen se remonta a 2004 cuando Ben Hammersley, periodista de The
Guardian, editor de Wired y autor de O'Reilly Media, acuñó el término.

Adam Curry, emprendedor de la Web, lo dio forma: a partir de RSS de
Dave Winner y Aaron Swartz, incorporar elementos para incluir archivos
adjuntos que fueran leídos por un software de reproducción de música
para iPod, el el iPodder.

Con el tiempo se ha asociado más podcast a archivo de audio que a
multimedia.

* Uso

Se utiliza para:
- Difundir contenidos específicos de una comunidad de intereses.
- Como un canal más de comunicación en una estrategia transmedia.
- Como un blog sonoro
- Un formato ágil de un medio especializados
- Un espacio de desarrollo de una idea o un tema.

* Formatos

Qué formatos encajan:

- Entrevistas
- Resumen de noticias
- Conversaciones
- Series

* Ejemplos

** Fellow the data
Fellow the data comenzó recientemente (20160418, dos episodios) para
hablar sobre el uso de los datos en la educación, las artes, el medio ambiente, la salud pública
y la innovación gubernamental.

Nace bajo la premisa del fundador Mike Bloomberg de que "si algo no puedes
medirlo, no puedes gestionarlo", y es lo que hace tan importante que
tenga que haber estrategias guiadas por datos que estén entre las que
determinan el éxito de un proyecto cualquiera.

Los podcasts comienzan con unxs invitados que compartirán sus
experiencias y proyectos sobre el impacto de los datos.

Se pueden descargar de iTunes o de SoundCloud.com/Follow-The-Data

https://soundcloud.com/follow-the-data/follow-the-data-podcast-episode-1-moving-beyond-coal

** Journalism News

El portal de periodismo de Reino Unido [[https://journalism.co.uk][journalism.co.uk]] lleva este
[[https://soundcloud.com/journalismnews][podcast]] sobre noticias, herramientas digitales y consejos para
periodistas y editores.

** Datastories

Un [[http://datastori.es/][podcast]] de visualización de datos con Enrico Bertini y Moritz
Stefaner. Con más de 40 programas, son una referencia fundamental. Aunque lo ponen en su propia web con un [[y][plugin de Wordpress]], también tienen un [[https://soundcloud.com/datastories][soundcloud]]

** La tecnología para todos
- URL: https://programarfacil.com/
- Podcast:
  http://www.ivoox.com/podcast-tecnologia-para-todos_sq_f1161932_1.html

De cada podcast hace un interesante artículo. Por ejemplo, el [[https://programarfacil.com/podcast/david-cuartielles-open-hardware/][108]] donde
entrevista a David Cuartielles, cofundador de Arduino y del Open
Hardware

** Autodefensa informática
   :PROPERTIES:
   :URL:      https://autodefensainformatica.radioalmaina.org/
   :Radio:    Radio Almaina
   :Ciudad:   Granada
   :Blog:     Wordpress
   :Podcast:  Archive.org
   :END:      

* Propuesta

Realizar unos cuantos podcast antes de junio de 2017 de las actividades relacionadas con el laboratorio de datos:
- 11 febrero, día de las mujeres y las niñas científicas, editatona de la Wikipedia.
- 14 febrero, ILOVEFS
- 4 marzo, día de los datos abiertos
- Abril, mayo y junio, taller de producción de periodismo de datos /La España vacía/
- 3-6 mayo, Jornadas de Periodismo de Datos.

** Duración

Por determinar
** Conversaciones

** Idiomas
- Español
- ¿Inglés?
